Pet-ner/AniDoc

backend/src/main/java/com/petner/anidoc/domain/user/pet/controller/DoctorPetController.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/controller/OwnerPetController.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/DoctorPetRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/DoctorPetResponseDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/OwnerPetRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/OwnerPetResponseDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/entity/Pet.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/DoctorPetRegistService.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/OwnerPetRegistService.java
backend/src/main/java/com/petner/anidoc/domain/user/user/repository/UserRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicalrecord/entity/MedicalRecord.java

이슈 링크 달아주세요. 
🔗 #2 
</br></br>
어떤 기능을 구현했는지 간단히 설명
✒️보호자 반려동물 등록 및 정보 수정, 관리자 반려동물 등록 및 정보 수정
</br></br>
✒️스웨거를 통해서 테스트완료
</br></br>
Closes #2

[FEAT] 반려동물 등록 및 정보수정 구현 #2

---

backend/src/main/java/com/petner/anidoc/domain/notice/controller/NoticeController.java
backend/src/main/java/com/petner/anidoc/domain/notice/dto/NoticeRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/notice/dto/NoticeResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/notice/entity/Notice.java
backend/src/main/java/com/petner/anidoc/domain/notice/repository/NoticeRepository.java
backend/src/main/java/com/petner/anidoc/domain/notice/service/NoticeService.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/controller/NotificationSseController.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/dto/NoticeNotificationDto.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/service/NotificationService.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/service/SseEmitters.java

🔗#10
</br></br>
✒️ 공지사항 작성, 수정, 삭제, 조회(전체 및 상세)
✒️ 공지사항 알림 데이터 로직 추가(공지의 content가 "." 까지만 담기)
✒️ 알림 기능 deadEmitter 처리 방식 변경
</br></br>
</br>
</br></br>
Closes #10

[FEAT] 공지사항 CRUD 구현, 알림 기능 일부 수정

---

backend/src/main/java/com/petner/anidoc/domain/vet/checkuprecord/controller/CheckupRecordController.java
backend/src/main/java/com/petner/anidoc/domain/vet/checkuprecord/repository/CheckupRecordRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/checkuprecord/service/CheckupRecordService.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicalrecord/entity/MedicalRecord.java
backend/src/main/java/com/petner/anidoc/domain/vet/surgeryrecord/controller/SurgeryRecordController.java
backend/src/main/java/com/petner/anidoc/domain/vet/surgeryrecord/entity/SurgeryRecord.java
backend/src/main/java/com/petner/anidoc/domain/vet/surgeryrecord/repository/SurgeryRecordRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/surgeryrecord/service/SurgeryRecordService.java

🔗https://github.com/Pet-ner/AniDoc/issues/19
</br></br>
✒️수술 기록 조회/수정/삭제(soft delete)
</br></br>
✒️h2 DB사용해서 swagger테스트
</br></br>
Closes #19

[FEAT] 수술기록 조회/수정/삭제

---

backend/src/main/java/com/petner/anidoc/domain/user/pet/controller/DoctorPetController.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/controller/OwnerPetController.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/repository/PetRepository.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/DoctorPetRegistService.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/OwnerPetRegistService.java

🔗
</br></br>
#30 
✒️ 보호자 및 의료진 반려동물 정보 전체 조회 및 상세조회 구현
</br></br>
✒️스웨거를 통해서 테스트완료
</br></br>
Closes #30

[FEAT] 반려동물 정보 전체 및 상세 조회구현 #30

---

backend/src/main/java/com/petner/anidoc/domain/chat/chatroom/service/ChatRoomService.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/OwnerPetRegistService.java
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/StaffResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/User.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/UserStatus.java
backend/src/main/java/com/petner/anidoc/domain/user/user/repository/UserRepository.java
backend/src/main/java/com/petner/anidoc/domain/user/user/service/UserService.java
backend/src/main/java/com/petner/anidoc/domain/vet/reservation/controller/ReservationController.java
backend/src/main/java/com/petner/anidoc/domain/vet/reservation/dto/DoctorAssignRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/reservation/dto/ReservationResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/reservation/entity/Reservation.java
backend/src/main/java/com/petner/anidoc/domain/vet/reservation/service/ReservationService.java
frontend/src/app/admin/reservations/page.tsx
frontend/src/app/layout.tsx
frontend/src/app/page.tsx
frontend/src/app/reservation/[id]/page.tsx
frontend/src/app/reservation/page.tsx
frontend/src/components/Sidebar.tsx
frontend/src/utils/formatDate.tsx
frontend/src/utils/formatDateToKorean.tsx

🔗#31
</br></br>
✒️프론트엔드 UI 개선
✒️유저, 예약 엔티티 수정
✒️예약 도메인 - 담당의 배정 관련 기능 추가
✒️진료 예약/관리 페이지 작업
</br></br>
✒️프론트, 백엔드 연동 테스트
</br></br>
Closes #31

[FEAT] FE - 진료 예약/관리 페이지

---

backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/DoctorPetRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/DoctorPetResponseDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/OwnerPetRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/OwnerPetResponseDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/entity/Pet.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/OwnerPetRegistService.java
frontend/src/app/doctorpet/page.tsx
frontend/src/app/ownerpet/page.tsx
frontend/src/components/Header.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/doctorpetchange/page.tsx
frontend/src/components/pet/page.tsx

🔗 #34 
</br></br>
✒️s3를 활용한 프로필사진등록 구현, 프론트 페이지 구현
</br></br>
✒️aws, 및 http://localhost:3000/ownerpet, http://localhost:3000/doctorpet
</br></br>
Closes #34

[FEAT] 로필사진등록 a3연결 및 심장사상충 누락사항 추가, 프론트 보호자 및 의료진 반려동물페이지 구현 #34

---

frontend/src/app/admin/reservations/page.tsx
frontend/src/components/HospitalCombobox.tsx

🔗#53
</br></br>
✒️취소 기능이 예약관리에 작성이 안되어있음 + 병원 컴포넌트 UI/UX 문제 해결
</br></br>
✒️UI/UX 개선, 필요한 기능이 빠져있었음
</br></br>
Closes #53

[REFACTOR] 예약 관리 페이지, 병원 선택 컴포넌트 수정

---

frontend/src/app/page.tsx

🔗#57
</br></br>
✒️대시보드 UI 수정
</br></br>
✒️UI 개선
</br></br>
Closes #57

[REFACTOR] 대시보드 UI 수정

---

backend/src/main/java/com/petner/anidoc/domain/user/pet/controller/DoctorPetController.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/controller/OwnerPetController.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/DoctorPetRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/DoctorPetResponseDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/OwnerPetRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/dto/OwnerPetResponseDTO.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/entity/Pet.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/DoctorPetRegistService.java
backend/src/main/java/com/petner/anidoc/domain/user/pet/service/OwnerPetRegistService.java
backend/src/main/java/com/petner/anidoc/global/security/SecurityConfig.java
frontend/next.config.ts
frontend/src/app/doctorpet/page.tsx
frontend/src/app/ownerpet/page.tsx
frontend/src/components/Header.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/doctorpetchange/DoctorChange.tsx
frontend/src/components/hospitalizationrecord/NewHospitalizationRecord.tsx
frontend/src/components/pet/PetRegist.tsx
frontend/src/components/pet/change/PetChange.tsx
frontend/src/components/pet/list/PetList.tsx

🔗 #50 
✒️삭제기능 구현
✒️프론트 api 연동 완료
✒️백엔드 코드 수정(중성화 여부 boolean → Boolean 등)
✒️스웨거, H2, 프론트(http://localhost:3000/ownerpet, http://localhost:3000/doctorpet)
Closes #50

[FEAT] 반려동물 등록 프론트 api연결및 백엔드 코드 수정 및 추가

---

backend/src/main/java/com/petner/anidoc/domain/notice/service/NoticeService.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/controller/NotificationController.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/controller/NotificationSseController.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/dto/NotificationDto.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/repository/NotificationRepository.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/service/NotificationService.java
backend/src/main/java/com/petner/anidoc/domain/user/notification/util/NotificationMessageUtil.java
frontend/src/app/admin/reservations/page.tsx
frontend/src/app/notices/[id]/edit/page.tsx
frontend/src/app/notices/[id]/page.tsx
frontend/src/app/notices/new/page.tsx
frontend/src/app/notices/page.tsx
frontend/src/app/page.tsx
frontend/src/components/Header.tsx
frontend/src/components/NotificationsList.tsx
frontend/src/components/NotificationsModal.tsx
frontend/src/components/RecentNotices.tsx
frontend/src/components/RecentReservations.tsx
frontend/src/components/Sidebar.tsx
frontend/src/utils/formatTimeForNotification.ts

🔗 #49 
</br></br>
✒️ 헤더의 알림 기능 구현 (드롭다운, 전체보기, 모두 읽음 처리, 정렬, 알림 개수 표시, 시간 포맷)
✒️ 최근 예약 컴포넌트 생성 
✒️ 공지사항 UI 개선 및 컴포넌트 생성
</br></br>
✒️ localhost:3000에서 테스트
</br></br>
Closes #49

[FEAT] 프론트 알림기능 및 최근 예약, 최근 공지사항 컴포넌트 구현. 공지사항 UI개선

---

backend/src/main/java/com/petner/anidoc/domain/user/user/controller/OAuth2UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/SocialSignUpRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/SocialSignUpResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/User.java
backend/src/main/java/com/petner/anidoc/domain/user/user/repository/UserRepository.java
backend/src/main/java/com/petner/anidoc/domain/user/user/service/UserService.java
backend/src/main/java/com/petner/anidoc/global/app/AppConfig.java
backend/src/main/java/com/petner/anidoc/global/rq/Rq.java
backend/src/main/java/com/petner/anidoc/global/security/CustomAuthorizationRequestResolver.java
backend/src/main/java/com/petner/anidoc/global/security/CustomOAuth2UserService.java
backend/src/main/java/com/petner/anidoc/global/security/CustomOauth2AuthenticationSuccessHandler.java
backend/src/main/java/com/petner/anidoc/global/security/CustomUserDetails.java
backend/src/main/java/com/petner/anidoc/global/security/SecurityConfig.java
backend/src/main/java/com/petner/anidoc/global/security/SecurityUser.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application.yml
frontend/src/app/auth-register/page.tsx
frontend/src/app/auth-register/staff/page.tsx
frontend/src/app/auth-register/user/page.tsx
frontend/src/app/login/page.tsx
frontend/src/contexts/UserContext.tsx

🔗#29
✒️ 카카오톡 로그인 기능 구현 
✒️ 카카오톡으로 회원 가입 진행 후 추가 정보 기입 시 유저로 저장 
Closes #29

[Feat] 소셜 로그인 추가 - 카카오

---

backend/src/main/java/com/petner/anidoc/domain/chat/chatmessage/controller/ChatController.java
backend/src/main/java/com/petner/anidoc/global/rq/Rq.java
backend/src/main/java/com/petner/anidoc/global/websocket/WebSocketAuthInterceptor.java
backend/src/main/java/com/petner/anidoc/global/websocket/WebSocketConfig.java

🔗#32
</br></br>
✒️웹소켓 인증 설정: 핸드셰이크 인터셉터 추가
</br></br>
✒️ 로컬 환경에서 프론트엔드, 백엔드 연동 테스트
</br></br>
Closes #32

[FEAT] 웹소켓 인증 설정

---

frontend/src/app/admin/reservations/page.tsx
frontend/src/components/Header.tsx
frontend/src/components/statistics/StatisticsPanel.tsx
frontend/src/components/statistics/components/PetTypeStats.tsx
frontend/src/components/statistics/components/StatCard.tsx
frontend/src/components/statistics/components/VisitStats.tsx
frontend/src/components/statistics/hooks/useStatistics.ts
frontend/src/components/statistics/types/statistics.ts

🔗 #74 
</br></br>
✒️ 예약관리 페이지에 들어갈 통계 컴포넌트 구현
✒️ 예약관리 페이지 헤더 추가
</br></br>
✒️ h2에 진료기록 테스트 데이터 삽입 후 localhost:3000에서 확인 
</br></br>
Closes #74

[FEAT] 통계 기능 프론트 구현

---

backend/src/main/java/com/petner/anidoc/domain/vet/medicine/controller/MedicineController.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/dto/MedicineRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/dto/MedicineResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/dto/MedicineSearchDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/dto/MedicineStockUpdateDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/entity/Medicine.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/repository/MedicineRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/service/MedicineService.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/controller/PrescriptionController.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/controller/PrescriptionManagementController.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/dto/PrescriptionRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/dto/PrescriptionResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/entity/Prescription.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/repository/PrescriptionRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/prescription/service/PrescriptionService.java
backend/src/main/java/com/petner/anidoc/global/exception/ErrorCode.java

🔗#77
</br></br>
✒️Medicine 도메인 백엔드 구현
✒️Prescription 도메인 백엔드 구현
</br></br>
✒️swagger 테스트
</br></br>
Closes #77

[FEAT] 약품 재고 관리 기능

---

frontend/src/app/login/page.tsx
frontend/src/app/notices/page.tsx

🔗 #99 
</br></br>
✒️프론트 배포를 위한 서스펜스 도입
</br></br>
</br>
✒️ localhost:3000
</br></br>
Closes #99

feat: 배포를 위한 서스펜스 도입

---

frontend/.env.production

🔗
</br></br>
✒️ env.production 오타 수정
</br></br>
✒️
</br></br>
Closes #99

[FIX]env수정

---

backend/src/main/java/com/petner/anidoc/domain/vet/checkuprecord/dto/CheckupRecordRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/checkuprecord/repository/CheckupRecordRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/checkuprecord/service/CheckupRecordService.java
backend/src/main/java/com/petner/anidoc/domain/vet/hospitalizationrecord/dto/HospitalizationRecordRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/hospitalizationrecord/repository/HospitalizationRecordRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicalrecord/controller/MedicalRecordController.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicalrecord/dto/FullMedicalRecordUpdateDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicalrecord/dto/MedicalRecordResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicalrecord/service/FullMedicalRecordService.java
backend/src/main/java/com/petner/anidoc/domain/vet/surgeryrecord/dto/SurgeryRecordRequestDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/surgeryrecord/repository/SurgeryRecordRepository.java
backend/src/main/resources/application.yml
frontend/package-lock.json
frontend/package.json
frontend/src/app/medical-records/edit/[id]/page.tsx
frontend/src/app/medical-records/page.tsx
frontend/src/components/medical-records/ChartDetailModal.tsx
frontend/src/components/medical-records/ChartModal.tsx
frontend/src/components/medical-records/StaffMedicalRecord.tsx
frontend/src/components/medical-records/UserMedicalRecord.tsx
frontend/src/types/medicalRecordTypes.ts

🔗https://github.com/Pet-ner/AniDoc/issues/90
</br></br>
어떤 기능을 구현했는지 간단히 설명
✒️진료차트에서 진료기록 및 입원,수술,검사 기록 수정
</br></br>
</br> http://localhost:3000, mySQL이용해서 테스트 완료
✒️
</br></br>
Closes #90

[FEAT] 진료차트 수정

---

frontend/src/app/doctorpet/page.tsx
frontend/src/app/medical-records/page.tsx
frontend/src/app/staff-management/page.tsx
frontend/src/components/Header.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/medical-records/StaffMedicalRecord.tsx
frontend/src/components/medical-records/UserMedicalRecord.tsx
frontend/src/components/staff-management/StaffApprovalList.tsx
frontend/src/components/staff-management/StaffList.tsx

🔗https://github.com/Pet-ner/AniDoc/issues/105
</br></br>
✒️ROLE_ADMIN일때 노출되게 할 직원관리 탭 프론트 디자인
</br></br>
</br>http://localhost:3000
✒️
</br></br>
Closes #105

[FEAT] 직원 관리 프론트 디자인

---

backend/src/main/java/com/petner/anidoc/domain/vet/medicine/controller/MedicineController.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/repository/MedicineRepository.java
backend/src/main/java/com/petner/anidoc/domain/vet/medicine/service/MedicineService.java
frontend/src/app/medicines/page.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/medicines/MedicineModal.tsx
frontend/src/types/medicine.ts

🔗#94
</br></br>
✒️재고 관리 페이지 작업
</br></br>
✒️localhost 테스트
</br></br>
Closes #94

[FEAT] 재고 관리 페이지 작업

---

backend/.gitignore
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/AdminController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/OAuth2UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/LoginResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/StaffResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/UserResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/ApprovalStatus.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/User.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/UserStatus.java
backend/src/main/java/com/petner/anidoc/domain/user/user/repository/UserRepository.java
backend/src/main/java/com/petner/anidoc/domain/user/user/service/UserService.java
backend/src/main/java/com/petner/anidoc/domain/user/user/service/UserStatusService.java
backend/src/main/java/com/petner/anidoc/global/exception/ErrorCode.java
backend/src/main/java/com/petner/anidoc/global/security/SecurityConfig.java
frontend/src/app/login/page.tsx
frontend/src/app/staff-management/page.tsx
frontend/src/components/ProfileSidebar.tsx
frontend/src/components/staff-management/StaffApprovalList.tsx
frontend/src/components/staff-management/StaffList.tsx
frontend/src/contexts/UserContext.tsx

🔗 #96 
</br></br>
✒️Admin이 의료진 가입 승인
✒️각자 Status를 프로필에서 수정할 수 있고, 그게 admin 페이지에서 반영됨.
✒️로그인 후 브라우저를 종료한 뒤 다시 브라우저를 열어 로그인으로 진입하면, 에러가 발생 
</br></br>
Closes #96

[FEAT] 의료진 가입 승인, status 수정, 로그인 에러 해결 

---

backend/.gitignore
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/AdminController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/OAuth2UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/controller/UserController.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/LoginResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/StaffResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/dto/UserResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/ApprovalStatus.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/User.java
backend/src/main/java/com/petner/anidoc/domain/user/user/entity/UserStatus.java
backend/src/main/java/com/petner/anidoc/domain/user/user/repository/UserRepository.java
backend/src/main/java/com/petner/anidoc/domain/user/user/service/UserService.java
backend/src/main/java/com/petner/anidoc/domain/user/user/service/UserStatusService.java
backend/src/main/java/com/petner/anidoc/global/exception/ErrorCode.java
backend/src/main/java/com/petner/anidoc/global/security/SecurityConfig.java
frontend/src/app/login/page.tsx
frontend/src/app/staff-management/page.tsx
frontend/src/components/ProfileSidebar.tsx
frontend/src/components/staff-management/StaffApprovalList.tsx
frontend/src/components/staff-management/StaffList.tsx
frontend/src/contexts/UserContext.tsx

🔗 #96 
</br></br>
✒️Admin이 의료진 가입 승인
✒️각자 Status를 프로필에서 수정할 수 있고, 그게 admin 페이지에서 반영됨.
✒️로그인 후 브라우저를 종료한 뒤 다시 브라우저를 열어 로그인으로 진입하면, 에러가 발생 
</br></br>
Closes #96

[FEAT] 의료진 회원가입 승인, Status 조회 및 개인 설정 가능 

---

backend/src/main/java/com/petner/anidoc/domain/vet/reservation/dto/ReservationResponseDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/vaccination/controller/DoctorPetVaccineController.java
backend/src/main/java/com/petner/anidoc/domain/vet/vaccination/dto/DoctorPetVaccineRequestDTO.java
backend/src/main/java/com/petner/anidoc/domain/vet/vaccination/dto/VaccinationStatusDto.java
backend/src/main/java/com/petner/anidoc/domain/vet/vaccination/service/DoctorPetVaccineService.java
frontend/src/app/medical-records/page.tsx
frontend/src/components/Sidebar.tsx
frontend/src/components/medical-records/StaffMedicalRecord.tsx
frontend/src/components/medical-records/VaccinationDetailModal.tsx
frontend/src/components/medical-records/VaccinationModal.tsx

🔗#118
</br></br>
✒️진료 기록에 접종 관리 추가
</br></br>
✒️
</br></br>
Closes #118

Refactor : 진료 기록에 접종 관리 추가 #118

---

frontend/src/app/login/page.tsx
frontend/src/components/Header.tsx

🔗https://github.com/Pet-ner/AniDoc/issues/120
</br></br>
✒️ui 수정
</br></br>
✒️
</br></br>
Closes #120

[FEAT] ui 수정

---

frontend/src/app/login/page.tsx
frontend/src/components/Header.tsx

이슈 링크 달아주세요. 
🔗
</br></br>
어떤 기능을 구현했는지 간단히 설명
✒️
</br></br>
✒️
</br></br>
Closes #

feat : ui 수정
